config/routes.rb
SmRc271::Application.routes.draw do
  resources :locations

  resources :snippets
  root 'snippets#index'
end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode  #need to call geocode mmethod when created or updated the address

  #to check pry
  def self.sample
   puts 'hii pry'
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all
    #debugger.pry
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        @snippet.update_attribute(:source_code, request.body)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @snippet }
      else
        format.html { render action: 'new' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:name, :language, :source_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text, lang)
    options = [:hard_wrap, :filter_html,  :gh_blockcode]
    Redcarpet.new(text, *options).to_html.html_safe
    #Pygments.highlight(text, lexer: lang ).html_safe
  end


end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmRc272</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :address %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div>
<% if true %>
    Hi
<% end %>
</div>
<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>


  <strong>Longitude:</strong>
  <%= @location.longitude %>

<p>
  <h4>Nearby Locations</h4>
  <% for loc in Location.near([@location.latitude, @location.longitude], 10) %>
    <li><%= link_to loc.address %>
      (<%= loc.distance.round(2) %> miles)</li>
<% end %>
</p>
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/snippets/_form.html.erb
<%= simple_form_for(@snippet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :language %>
    <%= f.input :source_code %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<h1>Listing snippets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Language</th>
      <th>Source code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @snippets.each do |snippet| %>
      <tr>
        <td><%= snippet.name %></td>
        <td><%= snippet.language %></td>
        <td><%= snippet.source_code %></td>
        <td><%= link_to 'Show', snippet %></td>
        <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
        <td><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @snippet.name %>
</p>

<p>
  <strong>Source code:</strong>
  <%= markdown(@snippet.source_code,@snippet.language ) %>
</p>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>